# Generated by Django 4.2.2 on 2023-06-11 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='category',
            field=models.ForeignKey(blank='true', default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='current_bid',
            field=models.DecimalField(blank='true', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='list',
            name='image_link',
            field=models.URLField(blank='true'),
        ),
    ]
