# Generated by Django 4.2.2 on 2023-07-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(null=True, upload_to='pfp'),
        ),
    ]
