# Generated by Django 4.2.2 on 2023-07-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(null=True, upload_to='media/pfp'),
        ),
    ]
