# Generated by Django 4.2.2 on 2023-07-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_likes_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
